apiVersion: v1
data:
  aws_access_key_id: QUtJQVVGNDYzVklJUU1XWTI3RlA=
  aws_secret_access_key: TGYzVmUzU2JEdGppd1RSbEhsMnlBcDRqU1ZJRkFNWkg4eUcwSDFTTQ==
  google_api_key: QUl6YVN5RFI3cFNsQS02ZVhZMEhJRGNuekoydXFfS1ZXWGxISXhr
kind: Secret
metadata:
  name: leafguard-api-secret
type: Opaque