apiVersion: v1
kind: Service
metadata:
  name: leafguard-ui-svc
spec:
  selector:
    app: leafguard-ui
  type: ClusterIP
  ports:
    - port: 80          # The port that the service will expose for HTTPS
      targetPort: 3000   # The port on the pod that the service will forward to
      protocol: TCP
