apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafguard-api
  labels:
    app: leafguard-api
  namespace: dev
spec:
  replicas: 0
  selector:
    matchLabels:
      app: leafguard-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::287559100945:role/aimlops-leafguard-eks-node-group-iam
      labels:
        app: leafguard-api
    spec:
      containers:
      - image: 287559100945.dkr.ecr.ap-south-1.amazonaws.com/aimlops-leafguard-api:latest
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: leafguard-api-secret
              key: google_api_key
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: leafguard-api-secret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: leafguard-api-secret
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            configMapKeyRef:
              name: leafguard-api-cfg
              key: aws_default_region
        imagePullPolicy: Always
        name: leafguard-api
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        
