apiVersion: v1
kind: Service
metadata:
  name: leafguard-api-svc
spec:
  selector:
    app: leafguard-api
  type: ClusterIP
  ports:
    - port: 80          # The port that the service will expose for HTTPS
      targetPort: 5000   # The port on the pod that the service will forward to
      protocol: TCP
